config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'brands#home'

  resources :customer_data, only: [:new, :create]


  resources :user_products, only: [:show, :create]

  resources :brands do
    resources :products
  end

  resources :products do
    resources :product_sizes, only: [:new, :create, :update, :destroy]
  end

  resources :product_sizes do
    collection do
      get :convert
    end
  end

  # resources :products do
  #   resources :products_sizes, only: [:new, :create]
  # end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_brandform.html.erb
<%#= form_for(@brand, url: new_brand_path) do |f| %>
<%#= form_for @brand do |f| %>
  <%#= f.label :name %>
  <%#= f.text_field :name %>
  <%#= f.button :submit, class: 'btn-brand-sign' %>
<%# end %>

<%= simple_form_for(@brand) do |f| %>
  <%= f.input :name %>
  <%#= f.submit value="Add" %>
  <%= f.button :submit, class: 'btn-brand-sign' %>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_form.html.erb
  <form>
  <div class="form-group">
    <label for="exampleInputEmail1">Brand Name</label>
    <input type="name" class="form-control" id="brandname" aria-describedby="brandname" placeholder="Brand Name">
    <%# <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small> %>
  </div>
  <div class="form-group">
    <label for="exampleInputEmail1">Email address</label>
    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Password</label>
    <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
  </div>
  <div class="form-check">
    <input type="checkbox" class="form-check-input" id="exampleCheck1">
    <label class="form-check-label" for="exampleCheck1">Check me out</label>
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_navbarblue.html.erb
<div class= "border-bottom border-warning navbar-blue">
  <div class="d-flex justify-content-between align-items-center container p-3">
    <%= link_to 'FitsMe', root_path, class: "h1" %>
    <div>
      <% if user_signed_in? %>
        <%= link_to 'User', edit_user_registration_path, class: "btn btn-nav" %>
      <% else %>
        <%= link_to 'Log In', new_user_session_path, class: "btn btn-nav" %>
      <% end %>
      <%= link_to 'Customer', new_customer_datum_path, class: "btn btn-nav" %>
      <%= link_to 'Brand', brands_path, class: "btn btn-nav" %>
    </div>
  </div>
</div>

app/views/shared/_oldform.html.erb
  <form>
  <div class="form-group">
    <label for="exampleInputEmail1">Brand Name</label>
    <input type="name" class="form-control" id="brandname" aria-describedby="brandname" placeholder="Brand Name">
    <%# <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small> %>
  </div>
  <div class="form-group">
    <label for="exampleInputEmail1">Email address</label>
    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Password</label>
    <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
  </div>
  <div class="form-check">
    <input type="checkbox" class="form-check-input" id="exampleCheck1">
    <label class="form-check-label" for="exampleCheck1">Check me out</label>
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>