config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'brands#home'

  resources :customer_data, only: [:new, :create]


  resources :user_products, only: [:show, :create]

  resources :brands do
    resources :products
  end

  resources :products do
    resources :product_sizes, only: [:new, :create, :update, :destroy]
  end

  resources :product_sizes do
    collection do
      get :convert
    end
  end

  # resources :products do
  #   resources :products_sizes, only: [:new, :create]
  # end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :users, dependent: :nullify
  has_many :products, dependent: :destroy
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
    include Pundit
    skip_after_action :verify_authorized, only: [:home, :new, :create]
    before_action :skip_authorization

    skip_before_action :authenticate_user!, only: [:home, :new, :destroy, :show, :index]

    def home
    end

    def new
      @brand = Brand.new
      authorize @brand
    end

    def create
      @brand = Brand.new(brand_params)
      authorize @brand

      @brand.user = current_user
      if @brand.save
        redirect_to new_brand_product_path(@brand)
      
      else
        render 'new'
      end
    end

    def show
      @brand = Brand.find(params[:id])
      authorize @brand

    end

    def index
      @brands = policy_scope(Brand)
    end

    def destroy
        @brand = Brand.find(params[:id])
        @brand.destroy
        redirect_to root_path
        authorize @brand
    end

    private

    def brand_params
      params.require(:brand).permit(:name)
    end
end

app/views/brands/home.html.erb
<div class="background">

        <div class="overlay" style=" position: absolute;width: 100%; height: 100vh;text-align: left;">

            <div class="col-md-12">
                <nav class="navbar" style="margin-top: 1%;">
                    <div class="navbar-brand">
                        <h1 class="log-1">Fits<span>Me</span></h1>
                    </div>
                    <ul class="nav" style="margin-right: 1%">
                        <%#= link_to 'Size Quiz', new_customer_datum_path, class: "nav-link", style:'color: white'%>
                        <li class="nav-item">
                            <%# <a href="#" class="nav-link">Sign in</a> %>
                            <% if user_signed_in?  %>
                              <%= link_to 'Log Out', edit_user_registration_path, class: "nav-link"%>
                            <% else %>
                              <%= link_to 'Sign in', new_user_session_path, class: "nav-link" %>
                            <% end %>
                        </li>
                    </ul>
                </nav>
            </div>

            <div class="info">
                <h2 class="text-left">Seamless Sizing, Brand Agnostic.</h2>
                <p class="text-left mb-5">
                    The World's top apparel companies use FitsMe to connect <br> clothing to customers, boost conversation and slash returns.
                </p>

                <a href="<%= products_path %>" class="button-main py-2 px-5 ">Brand</a>
                <a href="customer_data/new" class="button-main py-2 px-4 " style="margin-left:15px">SizeFinder</a>
            </div>

        </div>

    </div>

app/views/brands/index.html.erb
<!-- Start brand_product page Section-->

    <section class="home">
        <div class="main_container">
        </div>

        <div class="brand_products">
            <div class="container">
                <div class="row">
                  <h1 class="p-3">Returning?</h1>
                </div>
                <br>
                <%# <div class="row d-flex justify-content-center"> %>
                <div class= "d-flex justify-content-between align-items-center container p-3">
                  <%# <div class="index-grid"> %>
                   
                    <%= link_to 'New', new_brand_path, class: "btn-white-2"%>

                    <br>
                    <br>
                    <%= link_to 'Returning', new_brand_path, class: "btn-white-2"%>
                  <%# </div> %>
                </div>
                  </div> 
                </div>
                <br>
                <br>
            </div>

        </div>
    </section>

    <!-- End Start brand_product page Section--> 

app/views/brands/new.html.erb
<%# <div class="d-flex justify-content-between container p-5"> %>
<div class="home">
  <div class="brand-card-2" >
    <br>
    <br>
    <div class ="row">
    <div class="col-2">
      <div class= "brand-card-sm-2">
       <h1>Brand Registration</h1>
       <%= render 'shared/brandform' %>
      </div>
    </div>
    <div class = "col-1">
    </div>
    <div class="col-6">
      <%= image_tag 'FitQuiz1.jpg', style: "border-radius: 8px;
         width: 800px; height: 300px; margin: 10px; opacity: 1.0; border-color: $gray; position: static;
	top: 50px;"%>
    </div>
    </div>
    
    <%#= link_to 'Add your products', brand_products_path %>
  </div>
</div>

app/views/brands/show.html.erb
<p>show</p>