config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'brands#home'

  resources :customer_data, only: [:new, :create]


  resources :user_products, only: [:show, :create]

  resources :brands do
    resources :products
  end

  resources :products do
    resources :product_sizes, only: [:new, :create, :update, :destroy]
  end

  resources :product_sizes do
    collection do
      get :convert
    end
  end

  # resources :products do
  #   resources :products_sizes, only: [:new, :create]
  # end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :brand
  has_one_attached :photo
  has_many :product_sizes, dependent: :destroy
  validates :garment_type, inclusion: {in:  ["shirt", "pants", "jacket", "skirt", "dress", "sweater"] }
  validates :fabric_type, inclusion: {in: ["tight less than 5cm allowance", "medium +5 to 10cm allowance", "loose +10cm allowance"] }
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  include Pundit
  skip_after_action :verify_authorized, only: [:home, :new, :create]
  before_action :skip_authorization #

  skip_before_action :authenticate_user!, only: [:home, :new, :create]

  def new
    @user = current_user
    @brand = @user.brand
    # @brand = Brand.find(params[:brand_id])
    @product = Product.new
    @product.brand = @brand
    authorize @product

  end

  def create
    @user = current_user
    @brand = @user.brand
    @product = Product.new(product_params)
    # @brand = Brand.find(params[:brand_id])
    @product.brand = @brand
    authorize @product

    if @product.save!
      # redirect_to new_product_product_size_path(@product)
      redirect_to new_product_product_size_path(@product)
    else
      render 'new'
    end
  end

  def show
    @product = Product.find(params[:id])
    authorize @product

    @product_size = ProductSize.new

  end

  def index
    @product = policy_scope(Product)
    @product = Product.all
    @user = current_user
    @brand = @user.brand

  end

  def edit
    @product = Product.find(params[:id])
    authorize @product
  end

  def update
    @product = Product.find(params[:id])
    @product.update(product_params)
    if @product.save
      redirect_to @product
    else
      render :edit
   end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to root_path
    authorize @product
  end

  private

  def product_params
    params.require(:product).permit(:name, :garment_type, :fabric_type, :brand_id, :photo)
  end
end

app/views/products/edit.html.erb
 <div class="container">
  <div class="row1">
    <div class="bottom d-flex justify-content-flex-start">
      <ul>
        <% if user_signed_in?  %>
          <li style="font-size: 15px; padding: 5px 5px; color:white;">
            <i class="far fa-user"></i>
            <%= link_to 'Log Out', edit_user_registration_path, :style=>'color: white; font-size: 15px; justify-content:center;'%>
          </li>
        <% else %>
          <li style="font-size: 15px; padding: 5px 5px; color: white;">
            <i class="far fa-user"></i>
            <%= link_to 'Sign in', new_user_session_path, :style=>'color: white; font-size: 15px;' %>
          </li>
        <% end %>
      </ul>
    </div>
    <div>
      <div class="logo">
        <h1 style="margin-top: 24px;"><%= link_to "Fits", root_path, :style=>'color: white; font-weight: bold;' %>Me</h1>
      </div>
      <ul>
        <li><h3>Brand Dashboard</h3></li>
        <div class="d-flex">
          <li style="font-size: 15px;"> Upload Steps:</li>
        </div>
        <div class="d-flex">
          <li style="font-size: 15px; padding: 5px 5px;">1. Upload products</li>
        </div>
        <div class="d-flex">
          <li style="font-size: 15px; padding: 5px 15px;">2. Add available sizes</li>
        </div>
        <div class="d-flex">
          <li style="font-size: 15px; padding: 5px 30px;"> 3. Activate your products</li>
        </div>
        <div class="d-flex">
          <li style="font-size: 15px;"> Payment Center</li>
        </div>
         <div class="d-flex">
          <li style="font-size: 15px;"> Reports</li>
        </div>
      </ul>
    </div>
  </div>
    <div class="row2">
      <div class="content">
        <div class="index-grid2">
          <div class= "row">
            <div class = "col-8">
              <h1 style="color:$burntorange;"><b>Product Upload</b></h1>
              <h3> <em>Saenguin</em></h3>
              <p> <i class="fas fa-location-arrow"></i> 10 Spring Lane Cleveland, Ohio 10889
                &nbsp; &nbsp; <i class="fas fa-user"> </i> User Since: October 2020
              </p>
            </div>
            <div class = "col-4 justify-contents-center">
              <%= image_tag 'logo2.png', style: "border-radius: 8px;
                width: 200px; height: auto; margin: 2px; opacity: 1.0; border-color: $gray; box-shadow: 0 10px 20px 0 $grey;"%>
            </div>
          </div>
          <div class="row">
              <%= image_tag 'brandtime1b.png',
              style: "width: 90%; height: auto; margin: 5px; opacity: .7;"%>
          </div>
          <div class="row">
              <div class="col-8">
                <h3>Product Basic Information</h3>
                <p>Begin by entering a few details about the product being uploaded.</p>
                <div class="card-new ml-0">
                   <%= simple_form_for @product do |f| %>
                      <%= f.input :name, label: "Product Name",prompt: "Product Name" %>
                      <%= f.input :garment_type, label: "Garment Type", collection: ["shirt", "pants", "jacket", "skirt", "dress", "sweater"]%>
                      <%= f.input :fabric_type, label: "Fit Type", collection: ["tight less than 5cm allowance", "medium +5 to 10cm allowance", "loose + 10cm allowance"] %>
                      <%= f.input :photo, as: :file %>
                      <br>
                      <br>
                      <br>
                      <br>
                      <%= f.button :submit, value: "Save Product", class: "btn-orange-big",style: "margin-left: 0px; font-size: 20px; font-style: bold;" %>
                    <% end %>
                </div>
              </div>
              <div class="col-4 d-flex justify-content-flex-start align-items-center">
                <div class="index-grid2">
                  <div class="row d-flex justify-content-flex-start align-items-center" >
                  </div>
                  <div class="row bottom">
                    <%= link_to products_path, style: "color: grey; margin-left: 300px; margin-top: 20px; font-size: 15px;"%>
                  <i class="fas fa-long-arrow-alt-left"></i> Back to Brand
              
                  </div>
                </div>
                <%# <%= image_tag 'sewing2.jpg',
                style: "width: 90%; height: auto; margin: 5px; opacity: .9;"%>
              </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</body>

app/views/products/index.html.erb
<div class="container">
  <div class="row1">
    <div class="bottom d-flex justify-content-flex-start">
      <ul>
        <% if user_signed_in?  %>
          <li style="font-size: 15px; padding: 5px 5px; color:white;">
            <i class="far fa-user"></i>
            <%= link_to 'Log Out', edit_user_registration_path, :style=>'color: white; font-size: 15px; justify-content:center;'%>
          </li>
        <% else %>
          <li style="font-size: 15px; padding: 5px 5px; color: white;">
            <i class="far fa-user"></i>
            <%= link_to 'Sign in', new_user_session_path, :style=>'color: white; font-size: 15px;' %>
          </li>
        <% end %>
      </ul>
    </div>
    <div>
      <div class="logo">
        <h1 style="margin-top: 24px;"><%= link_to "Fits", root_path, :style=>'color: white; font-weight: bold;' %>Me</h1>
      </div>
      <ul>
        <li><h3>Brand Dashboard</h3></li>
        <div class="d-flex">
          <li style="font-size: 15px;"> Upload Steps:</li>
        </div>
        <div class="d-flex">
          <li style="font-size: 15px; padding: 5px 5px;"> 1. Upload products</li>
        </div>
        <div class="d-flex">
          <li style="font-size: 15px; padding: 5px 15px;">2. Add available sizes</li>
        </div>
        <div class="d-flex">
          <li style="font-size: 15px; padding: 5px 30px;"> 3. Activate your products</li>
        </div>
        <div class="d-flex">
          <li style="font-size: 15px;"> Payment Center</li>
        </div>
         <div class="d-flex">
          <li style="font-size: 15px;"> Reports</li>
        </div>
      </ul>
    </div>
  </div>
  <div class="row2">
    <div class="content">
      <div class="index-grid2">
        <div class="row">
          <div class="col-3">
            <div class="card-brand">
              <%= image_tag 'brand2.jpg', style: "border-radius: 8px;
              width: 200px; height: 200px; margin: 2px; opacity: 1.0; border-color: white;"%>
            </div>
          </div>
          <div class="col-9 justify-contents-center">
            <h1><b>Welcome Back,<em><%= @brand.name.capitalize %></em></b></h1>
            <p>
              <i class="fas fa-location-arrow"></i> 10 Spring Lane Cleveland, Ohio 10889
              &nbsp; &nbsp;
              <i class="fas fa-user"></i> User Since: October 2020
            </p>
            <h3>Alerts and Updates</h3>
            <p><i class="fas fa-exclamation-circle"></i> Increased Returns of Medium for Navy Blazer </p>
            <p><i class="fas fa-exclamation-circle"></i> Size Large for White Blouse almost out of stock  </p>
          </div>
        </div>
        <div>
          <br>
          <div class="row" style="border-top: 1px solid lightgrey; width: 80vw; padding-top: 8px;" >
            <h3 style="margin-left: 30px;"><b><%= @brand.name.capitalize %> Product History</b></h3>
          </div>
          <div class="row mt-5">
            <div class="col-3">
              <div class="card-left mr-3">
                <div class="justify-content-right align-items-center">
                  <div class="row justify-content-right align-items-center" style="margin-left: 30px;">
                    <h3 style="font-size: 20px; font-weight: 700;">Product Quick Stats</h3>
                    <br>
                    <p style="size:18px; color: grey; font-weight: bold;"> <i class="far fa-arrow-alt-circle-up"></i> Medium is your most commonly ordered size</p>
                    <p style="size:18px; color: grey; font-weight: bold;"><i class="fas fa-bomb"></i> Extra Large is your most commonly returned size</p>
                    <p style="size:18px; color: grey; font-weight: bold;"><i class="fas fa-exclamation"></i>  Sales Volumes are lower than in Prevous Quarter</p>
                  </div>
                </div>
              </div>
            </div>

            <div class="col-9">

              <div class="row">
                <h3>Products  </h3> <%= link_to "+", new_product_path(@brand), class: "plus-link", style:"margin-right: 5px;" %>
              </div>
              <div class="size-grid justify-contents-center">

                <% @product.each do |product| %>
                  <div class="card-index d-flex justify-content-center">
                    <%= link_to product_path(product) do %>
                      <% if product.photo.attached? %>
                        <%= cl_image_tag product.photo.key, style: "object-fit: cover; border-radius: 8px; width: 105px; height: 110px; margin: 8px; opacity: 1.0; border-color: $gray;" %>
                        <p><%= product.name %></p>
                      <% else %>
                        <%= image_tag 'noimage.jpg', style: "object-fit: cover; border-radius: 8px;  width: 105px; height: 110px; margin: 8px; opacity: 1.0; border-color: $gray;" %>
                        <p><%= product.name %></p>
                      <% end %>
                    <% end %>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/products/new.html.erb
 <div class="container">
  <div class="row1">
    <div class="bottom d-flex justify-content-flex-start">
      <ul>
        <% if user_signed_in?  %>
          <li style="font-size: 15px; padding: 5px 5px; color:white;">
            <i class="far fa-user"></i>
            <%= link_to 'Log Out', edit_user_registration_path, :style=>'color: white; font-size: 15px; justify-content:center;'%>
          </li>
        <% else %>
          <li style="font-size: 15px; padding: 5px 5px; color: white;">
            <i class="far fa-user"></i>
            <%= link_to 'Sign in', new_user_session_path, :style=>'color: white; font-size: 15px;' %>
          </li>
        <% end %>
      </ul>
    </div>
    <div>
      <div class="logo">
        <h1 style="margin-top: 24px;"><%= link_to "Fits", root_path, :style=>'color: white; font-weight: bold;' %>Me</h1>
      </div>
      <ul>
        <li><h3>Brand Dashboard</h3></li>
        <div class="d-flex">
          <li style="font-size: 15px;"> Upload Steps:</li>
        </div>
        <div class="d-flex">
          <li style="font-size: 15px; padding: 5px 5px;">1. Upload products</li>
        </div>
        <div class="d-flex">
          <li style="font-size: 15px; padding: 5px 15px;">2. Add available sizes</li>
        </div>
        <div class="d-flex">
          <li style="font-size: 15px; padding: 5px 30px;"> 3. Activate your products</li>
        </div>
        <div class="d-flex">
          <li style="font-size: 15px;"> Payment Center</li>
        </div>
         <div class="d-flex">
          <li style="font-size: 15px;"> Reports</li>
        </div>
      </ul>
    </div>
  </div>
    <div class="row2">
      <div class="content">
        <div class="index-grid2">
          <div class= "row">
            <div class = "col-8">
              <h1 style="color:$burntorange;"><b>Product Upload</b></h1>
              <h3> <em><%= @brand.name.capitalize %></em></h3>
              <p> <i class="fas fa-location-arrow"></i> 10 Spring Lane Cleveland, Ohio 10889
                &nbsp; &nbsp; <i class="fas fa-user"> </i> User Since: October 2020
              </p>
            </div>
            <div class = "col-4 justify-contents-center">
              <%= image_tag 'logo2.png', style: "border-radius: 8px;
                width: 200px; height: auto; margin: 2px; opacity: 1.0; border-color: $gray; box-shadow: 0 10px 20px 0 $grey;"%>
            </div>
          </div>
          <div class="row">
              <%= image_tag 'brandtime1b.png',
              style: "width: 90%; height: auto; margin: 5px; opacity: .7;"%>
          </div>
          <div class="row">
            <div class="col-8">
              <h3>Product Basic Information</h3>
              <p>Begin by entering a few details about the product being uploaded.</p>
              <div class="card-new ml-0">
                <%= simple_form_for @product do |f| %>
                  <%= f.input :name, label: "Product Name",prompt: "Product Name" %>
                  <%= f.input :garment_type, label: "Garment Type", collection: ["shirt", "pants", "jacket", "skirt", "dress", "sweater"]%>
                  <%= f.input :fabric_type, label: "Fit Type", collection: ["tight less than 5cm allowance", "medium +5 to 10cm allowance", "loose + 10cm allowance"] %>
                  <%= f.input :photo, as: :file %>
              </div>
            </div>
            <div class="col-4 d-flex justify-content-flex-start align-items-center">
              <div class="index-grid2">
                <div class="row d-flex justify-content-flex-start align-items-center" >
                  <%= f.button :submit, value: "Save Product", class: "btn-orange-big",style: "margin-left: 0px; font-size: 20px; font-style: bold;" %>
                  <% end %>
                </div>
                <div class="row bottom">
                  <%= link_to products_path, style: "color: grey; margin-left: 300px; margin-top: 20px; font-size: 15px;" do %>
                <i class="fas fa-long-arrow-alt-left"></i> Back to Brand
                <% end %>
                </div>
              </div>
              <%# <%= image_tag 'sewing2.jpg',
              style: "width: 90%; height: auto; margin: 5px; opacity: .9;"%>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</body>

app/views/products/show.html.erb
<body>
  <div class="container">
    <div class="row1">
        <div class="bottom d-flex justify-content-flex-start">
          <ul>
          <% if user_signed_in?  %>
            <li style="font-size: 15px; padding: 5px 5px; color:white;"> <i class="far fa-user"></i> <%= link_to 'Log Out', edit_user_registration_path, :style=>'color: white; font-size: 15px; justify-content:center;'%></li>
          <% else %>
            <li style="font-size: 15px; padding: 5px 5px; color: white;"><i class="far fa-user"></i><%= link_to 'Sign in', new_user_session_path, :style=>'color: white; font-size: 15px;' %></li>
          <% end %>
          </ul>
        </div>
      <div class="logo">
        <h1><%= link_to "Fits", root_path, :style=>'color: white; font-weight: bold;' %>Me</h1>
      </div>
      <ul>
        <li><h3>Brand Dashboard</h3></li>
        <div class="d-flex">
          <li style="font-size: 15px;"> Upload Steps:</li>
        </div>
        <div class="d-flex">
          <li style="font-size: 15px; padding: 5px 5px;"> 1. Upload products</li>
        </div>
        <div class="d-flex">
          <li style="font-size: 15px; padding: 5px 15px;">2. Add available sizes</li>
        </div>
        <div class="d-flex">
          <li style="font-size: 15px; padding: 5px 30px;"> 3. Activate your products</li>
        </div>
        <div class="d-flex">
          <li style="font-size: 15px;"> Payment Center</li>
        </div>
         <div class="d-flex">
          <li style="font-size: 15px;"> Reports</li>
        </div>
      </ul>
    </div>
  <div class="row2">
    <div class="content" style="height: 100vh;">
      <div class="index-grid2">
        <div class= "row">
          <div class = "col-8" >
            <h1 style="color:$burntorange;">Snapshot: <b><%= @product.name %><b></h1>
            <h3> <em>Saenguin</em></h3>
            <p> <i class="fas fa-location-arrow"></i> 10 Spring Lane Cleveland, Ohio 10889
              &nbsp; &nbsp; <i class="fas fa-user"> </i> User Since: October 2020
            </p>
          </div>
          <div class = "col-4 justify-contents-center">
            <%= image_tag 'logo2.png', style: "border-radius: 8px;
                width: 200px; height: auto; margin: 2px; opacity: 1.0; border-color: $gray; box-shadow: 0 10px 20px 0 $grey;"%>
          </div>
        </div>
         <div class="row">
              <%= image_tag 'brandtime3b.png', style: "
            width: 90%; height: auto; margin: 5px;"%>
          </div>
        <div class="row">
          <div class="col-6 justify-content-center align-items-center p-3">
            <h3><b><%= @product.name %><b>: Product Details</h3>
               <div>
                 <p><b><i class="fas fa-tshirt"></i><b>  <%= @product.garment_type.capitalize %>  
                   &nbsp; &nbsp;<b><i class="fas fa-cut"></i><b>  <%= @product.fabric_type.capitalize %></p>
                </div>
                <div>
              <h3>Available in these Sizes</h3>
              <div class="row p-3">
                <div class="psize-grid">
              <% @product.product_sizes.each do |size| %>
                  <p style="align-content: center;"><i class="fas fa-check-square">&nbsp;</i><%=size.size_name %></p>
              <% end %>
                </div>
              </div>
              </div>

              <div class="row d-flex justify-content-flex-start">
              
                <%= link_to " Add Size", new_product_product_size_path(@product), :style=>"color:black; margin-right: 30px;", :class=>'btn-orange-big'  %>
            
                <% if @product.product_sizes.size >= 5%>
                  <%= link_to "Activate", convert_product_sizes_path(product_sizes: @product.product_sizes.map(&:id), product_id: @product), :class=>"btn-orange-big", :style=>"color:black;" %>
                <%end %>
            </div>
            </div>
          <div class="col-6">
           <div class="index-grid2 justify-contents-center align-items-center p-3">
            <% if @product.photo.attached?%>
              <%= cl_image_tag @product.photo.key, style: "object-fit: cover; border-radius: 8px;
                 width: 300px; height: auto; margin: 5px 5px; opacity: 1.0; border-color: $gray; justify-content:center; align-items: center;" %>
                 <div class="row">
                   <%= link_to "Update #{@product.name}",
                   edit_product_path(@product), style: "color: grey; font-size:12px; margin-top: 20px; margin-left: 10px;"%>
                   <%= link_to "Delete #{@product.name}",
                      product_path(@product), style: "color: grey; font-size:12px; margin-top: 20px; margin-left: 10px;",
                      method: :delete,
                      data: { confirm: "Are you sure" } %>
                 </div>
                 <div class="row">
                   <%= link_to "Back to Gallery", products_path, style: "margin-left: 10px; color: black; font-size: 20px;"%>
                 </div>
              <%# </p><b>Product Name: <b><%= @product.name %>
            <%else%>
              <%= image_tag 'noimage.jpg', style: "object-fit: cover; border-radius: 8px;
                  width: 300px; height: auto; margin: 5px 5px; opacity: 1.0; border-color: $gray; justify-content:center; align-items: center; "%>
                  <div class="row">
                    <%= link_to "Update #{@product.name}",
                    edit_product_path(@product), style: "color: grey; font-size:12px; margin-top: 20px; margin-left: 10px;"%>
                    <%= link_to "Delete #{@product.name}",
                      product_path(@product), style: "color: grey; font-size:12px; margin-top: 20px; margin-left: 10px;",
                      method: :delete,
                      data: { confirm: "Are you sure" } %>
                  </div>
                  <div class="row">
                   <%= link_to "Back to Gallery", products_path, style: "margin-left: 20px; color: black; font-size: 20px;"%>
                 </div>
             <%end%>
            </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  </div>
    <%# </div>
  </div> %>
</body>